apiVersion: v1
kind: Service
metadata:
  name: {{ include "trama-gateway.fullname" . }}-control-plane
  labels:
    {{- include "trama-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "trama-gateway.name" . }}
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.controlPlane.service.port }}
      targetPort: http
