{{- if .Values.pythonApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trama-gateway.fullname" . }}-python-api
  labels:
    {{- include "trama-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "trama-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: python-api
  ports:
    - name: http
      port: {{ .Values.pythonApi.service.port }}
      targetPort: http
{{- end }}
